/**
 * Regenerates src/db/embedded-migrations.ts from the current drizzle/ folder.
 * Run after: bun run db:generate
 *
 * Usage: bun run db:embed
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, basename } from "node:path";

const DRIZZLE_DIR = "./drizzle";
const OUT_FILE = "./src/db/embedded-migrations.ts";

const sqlFiles = readdirSync(DRIZZLE_DIR)
  .filter((f) => f.endsWith(".sql"))
  .sort();

if (sqlFiles.length === 0) {
  console.error("No .sql files found in ./drizzle — run bun run db:generate first");
  process.exit(1);
}

const imports = sqlFiles
  .map((f, i) => `import m${i} from "../../drizzle/${f}" with { type: "text" };`)
  .join("\n");

const entries = sqlFiles
  .map((f, i) => {
    const name = basename(f, ".sql");
    return `  { name: "${name}", sql: m${i} },`;
  })
  .join("\n");

const content = `\
/**
 * SQL migrations embedded at build time via Bun import attributes.
 * Used by MigrationManager when running as a compiled binary.
 *
 * Auto-generated by: bun run db:embed
 * Do not edit manually — re-run after bun run db:generate
 */
${imports}

export const EMBEDDED_MIGRATIONS: Array<{ name: string; sql: string }> = [
${entries}
];
`;

writeFileSync(OUT_FILE, content, "utf8");
console.log(`✅ Wrote ${sqlFiles.length} migration(s) to ${OUT_FILE}`);
for (const f of sqlFiles) console.log(`   → ${f}`);
